Scorpio "GuildBankSort.Localization.zhCN" ""

local L = _Locale("zhCN",true)

L["guild_bank_sort_button_tooltip"] = "鼠标左键点击整理\n右键点击打开物品转移对话框\n\n|cffff0000如果你频繁整理失败（每次整理完再次点击整理按钮仍然会出现整理进度条），请ALT+鼠标左键配置整理间隔，间隔越大，成功率越高！|r"
L["guild_bank_merge_items"] = "正在合并物品(%d/%d)"
L["guild_bank_move_items"] = "正在移动物品(%d/%d)"
L["guild_bank_cannot_withdraw"] = "你的提取额度不足！"
L["guild_bank_cannot_deposit"] = "该标签你无法存放物品！"
L["guild_bank_transfer_dialog_title"] = "公会银行物品转移"
L["guild_bank_transfer_src_title"] = "来源标签页：|T%s:15|t%s（第%d页）"
L["guild_bank_transfer_filter_default"] = "任意"
L["guild_bank_transfer_class_filter_title"] = "物品类型"
L["guild_bank_transfer_subclass_filter_title"] = "物品子类型"
L["guild_bank_transfer_expac_filter_title"] = "资料片"
L["guild_bank_transfer_quality_filter_title"] = "稀有程度"
L["guild_bank_transfer_add_item_tooltip"] = "右键添加此物品至待转移区域"
L["guild_bank_transfer_remove_item_tooltip"] = "右键从待转移区域中移除此物品"
L["guild_bank_transfer_src_transfer_all"] = "全部转移"
L["guild_bank_transfer_waiting_title"] = "待转移物品："
L["guild_bank_transfer_waiting_transfer_clear_all"] = "清除全部"
L["guild_bank_transfer_to_bag"] = "转移至背包"
L["guild_bank_transfer_to_bag_confirm"] = "确定转移至背包？"
L["guild_bank_transfer_to_bag_description"] = "提取物品(%d/%d)"
L["guild_bank_transfer_to_other_tab"] = "转移至其它标签"
L["guild_bank_transfer_to_other_tab_picker_label"] = "标签页："
L["guild_bank_transfer_to_other_tab_picker_default"] = "请选择"
L["guild_bank_transfer_to_other_tab_picker_text"] = "%s(%d)"
L["guild_bank_transfer_to_other_tab_retrive_data"] = "正在获取目标标签页信息，请稍等"
L["guild_bank_transfer_to_other_tab_full"] = "目标标签页没有空栏位？"
L["guild_bank_transfer_to_other_tab_description"] = "正在转移物品(%d/%d)"
L["guild_bank_transfer_to_other_tab_confirm"] = "确定转移物品至|T%s:15|t%s（第%d页）？"
L["guild_bank_config_dialog_title"] = "公会银行整理配置项"
L["guild_bank_config_pickup_interval"] = "整理间隔"